### PR TITLE
Homework1 take2

### PR DESCRIPTION
**Pull request by ngokli**
@iroy2000: I'm not sure if you're the one who is going to be looking at this, but here's my solution for the first homework problem. As for the second homework problem, I am a bit confused about the expected behaviour... The examples seem inconsistent. Should I address that with you or Marina?

Sorry for not using the Redux state in my solution. It took me quite a while to grok the boilerplate and all the associated frameworks, as node.js, React, Redux, etc. are all new to me. My focus has been more backend in recent years. Also, I'm coming back to software engineering after a sabbatical, so it takes me a bit to warm up again. I appreciate your bearing with me!

### CODE REVIEW

**Comment by iroy2000** [comment]
@ngokli you can leave your question here if you are confused.  Let me elaborate the 2nd question more here :
- Take as example the string `blabla`:  we should output all possible values { a: 3, b:3, l:3, bl: 2, la: 2, bla: 2 } ? 

You will need to output all possible values, not the longest duplicated substring. So overlap is fine.
For instance, `blablabla` could contain 2 b, 3 bl, 3 bla, 3 blab, 2 blabl, 2 blabla, etc ...

**Comment by ngokli** [comment]
Ah, you caught my confusion!  So the example "bbbaacbbbaa --> (bbbaa) = 2, (a) = 4, (b) = 6" is missing some of the output, right?  I was confused because the output has both the longest duplicated substring and shortest duplicated substrings, but nothing in between!

I'll whip something up now...

Just to be sure, this is the correct output, right?

| Substring | Count |
| --- | --- |
| b | 6 |
| bb | 4 |
| bbb | 2 |
| bbba | 2 |
| bbbaa | 2 |
| bba | 2 |
| bbaa | 2 |
| ba | 2 |
| baa | 2 |
| a | 4 |
| aa | 2 |

**Comment by iroy2000** [comment]
Yes, you are right!

**Comment by iroy2000** [comment]
Btw, our company name is Chegg :p

**Comment by ngokli** [comment]
Oh no!  A little sleep deprivation :(

**Pull request closed without merging**
